name: Deploy to production

on:
    workflow_dispatch:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: SSH to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      cd /home/projects/klima-merks
                      git checkout .
                      git pull origin master
                      docker build -t klima-merks-frontend .
                      docker inspect klima-merks >/dev/null 2>&1 && docker stop klima-merks && docker rm klima-merks || echo "klima-merks not found. Skipping stop."
                      docker run -d --restart always -p 3002:3000 --name klima-merks klima-merks-frontend
                      docker rmi $(docker images -f dangling=true -q)
